### ISSUE TITLE
Cannot add group members

### ISSUE THREAD

**Issue by laserlab** [ubsuny/23-Homework1G3#1]
Please have a look here:

https://github.com/ubsuny/23-Homework1G1/issues/1

And do the same in this repository

**Comment by JustinJaniszewski** [comment]
Understood, will do this as soon as I get their usernames.

**Comment by laserlab** [comment]
Just ask on discord. Should be the fastest.

**Comment by JustinJaniszewski** [comment]
One member's username is reshnashrestha. I do not know the other one's discord. I was waiting on them to message me. If I find out I will let you know.

**Comment by laserlab** [comment]
You can also just ask everyone in the homework channel the mention link in discord for the whole class is @student 410-2023 
If you want to mention the whole class in an GitHub item use @ubsuny/cp23-1

**Comment by laserlab** [comment]
I added @reshnashrestha to the group 1 team (@ubsuny/hw1g1_cp23-1 )

**Comment by reshnashrestha** [comment]
Hi,
Am I on group HW1G3_CP23-1 or HW1G1_CP23-1?
Best,
Reshna
________________________________

**Comment by pratibha77118** [comment]
Hi Justin ! I am the other member of your group. Please add me on it. My github username is pratibha77118

**Comment by JustinJaniszewski** [comment]
I believe you're all set if you were able to comment that. I am going to go ahead and close this issue.

**Comment by reshnashrestha** [comment]
I believe that she is not added yet to the group.  
![Screenshot_20230909_163531_Samsung Internet](https://github.com/ubsuny/23-Homework1G3/assets/143649458/c4af0db8-aa14-4f3f-a8b6-997d8e51f594)

**Comment by reshnashrestha** [comment]
@JustinJaniszewski I don't think @pratibha77118 is added to the group yet. 
As I am seeing only we 2 in G3 
![image](https://github.com/ubsuny/23-Homework1G3/assets/143649458/5e59aae1-1828-4c72-ab70-f04f0d975788)

**Comment by pratibha77118** [comment]
@laserlab Can you add me to this 
(G3)?

**Comment by laserlab** [comment]
Done, if everything works, close this issue
