### ISSUE TITLE
Any idea on implementing division function on quantam computer?

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G3#13]
How do I start to use division function on Quantum  computer? Any suggestion / reference tutorial is highly appreciated .

**Comment by JustinJaniszewski** [comment]
I understand it might be complicated to tell a quantum computer to divide. Apparently, a way to do this may be something called the "restoring division algorithm". Essentially, you are telling the quantum computer to think of division in terms of repeated subtraction. You could keep subtracting the denominator from the numerator. This would go on looped. Every loop you would subtract the denominator from the numerator but also add 1 to the quotient (starting off at zero).

**Comment by JustinJaniszewski** [comment]
#15 Checking this file out would better explain it

**Comment by JustinJaniszewski** [comment]
I've created this file to help explain what I mean #15 . I will also paste below so it may be easier to read:

`#Example: 10 divided by 3:
def restoring_division(numerator, denominator):
  quotient = 0 #answer to division problem, set to zero for now
  #set the remainder to the numerator, 10 (this will get subtracted later)
  remainder = numerator

  #as long as the remainder (currently 10)...
  #is big enough to be subtracted by the denominator (3) we can run this code:
  while remainder >= denominator:
    
    #this counts each individual time 3 can go into 10
    quotient += 1
    
    #after the first subtraction, the remainder is set to 7, from (10 - 3)
    remainder -= denominator

  #after it subtracts 3 times, it cannot subtract anymore, meaning the quotient is 3
  #we can also return the remainder, which is anything that is left over
  #will return (3,1)
  return quotient, remainder`

**Comment by reshnashrestha** [comment]
@ubsuny/cp23-1 if anyone has idea about this?

**Comment by reshnashrestha** [comment]
> I've created a file to help explain what I mean. I am having trouble posting the code correctly below so I would recommend checking it out here #15 .

I checked on #15, the code is on Python. So how could it possibly run on a quantum computer? I believe that there should be a use of "import Qiskit" and all, I am still trying to figuring it out.

**Comment by reshnashrestha** [comment]
We can try using Qiskit in Python.
