### ISSUE TITLE
Documentation/ Division function

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G3#16]
How to start on the documentation part? @ubsuny/cp23-1

**Comment by poojashresthacode** [comment]
Hey reshna..I am also doing documentation. I will be writting the documentation for each command or line in the code

**Comment by reshnashrestha** [comment]
Oh, I am planning on the same process from the very beginning. 
@poojashresthacode have you started?

**Comment by JustinJaniszewski** [comment]
You could have docstrings in the coding file as well as a README file to explain how to use the code. I will give an example of a docstring:
`#this function divides a by b
def divsion(a,b):`

**Comment by pratibha77118** [comment]
@JustinJaniszewski  we can only test the python file after we run and verify the division function in quantam computer.
