### ISSUE TITLE
Question about what to be include in the Algorithm, Documentation and Unit test.

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G3#17]
Do I have to include the state vector, probabilities or the Q-sphere graphs in the Algorithm or the unit test part??

What are the important things to be included??

**Comment by reshnashrestha** [comment]
@ubsuny/cp23-1 any insights on this ?

**Comment by reshnashrestha** [comment]
@yasmensarhan27 did you find anything ? Share with me as well.
