### ISSUE TITLE
Division Function Complication

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G3#19]
Implementing classical arithmetic functions like division on a quantum computer may not be the most efficient or practical use of quantum resources. Source: **Chatgpt**

**Comment by reshnashrestha** [comment]
How are we going to run this ? @pratibha77118 @JustinJaniszewski

**Comment by reshnashrestha** [comment]
I was searching for how to begin to implement the division function, and I found this kind of stuff:

**Performing basic arithmetic operations like division on a quantum computer is highly inefficient and not what quantum computing is designed for. 
The use of Python and Qiskit to simulate division on a quantum computer is not a practical application.** 

Source: **chatgpt** 

@laserlab in your suggestion what do you want us to choose as an arithmetic function for our group homework?

**Comment by JustinJaniszewski** [comment]
I don't believe it matters if it is inefficient. I would recommend checking out #13 . And the restoring_division_example.py in the main branch. It shows how to do division in terms of subtraction.
