### ISSUE TITLE
Arithmetic Function

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G3#2]
Hi, group members! Let's discuss which arithmetic function are we implementing in our homework. We must let other groups know as we can't use similar functions.

**Comment by reshnashrestha** [comment]
As the G4 has chosen, multiplication, I am thinking we can go with addition. Please share your views on this.

**Comment by Pranjal-Srivastava-2023** [comment]
> As the G4 has chosen, multiplication, I am thinking we can go with addition. Please share your views on this.

@reshnashrestha we in G2 have chosen addition too.

**Comment by reshnashrestha** [comment]
The functions already taken are:
G5 subtraction
G4 multiplication
G2 addition
So, I think we are behind on this. Lets discuss for our function @JustinJaniszewski @pratibha77118

**Comment by pratibha77118** [comment]
Yes we need to decide on this soon. I think we should go for division or Modulus.

**Comment by JustinJaniszewski** [comment]
sorry for the late response. I think we can go for division.

**Comment by pratibha77118** [comment]
Let's finalize on division function for our group.

**Comment by reshnashrestha** [comment]
> Also we need to inform other groups that we are using division function. How to inform them @JustinJaniszewski and @reshnashrestha ? Further, we should allocate different tasks to each one of us like developing algorithms, documentation and unit test too.

Yes I will do it.

**Comment by reshnashrestha** [comment]
We are lagging behind the discussion part. 
Division finalized from our side

**Comment by pratibha77118** [comment]
Now that  the division function is finalized. We should plan on how to use the function starting from algorithm to developing code to execute it. How do we pLan on it? @JustinJaniszewski @reshnashrestha  share about what you have understood..

**Comment by JustinJaniszewski** [comment]
i think first we should assign roles. The professor lists them as "developing algorithm, documentation, unit test". Do you guys have any preference? Ones these are assigned we can help each other if needed.

**Comment by reshnashrestha** [comment]
So @JustinJaniszewski on which page of understanding are you on programming? I am a novice at this and need some help and guidance about programming on QC and all.

**Comment by JustinJaniszewski** [comment]
I wouldn't say im great however I took a semster of computer science and did some coding in high school. At least for the purposes of this homework,  I shouldn't have an issue.

**Comment by reshnashrestha** [comment]
Division function is decided.
