### ISSUE TITLE
Branch deletion

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G3#24]
@JustinJaniszewski have you deleted my branch from the main homework repo after merging? Because having a new branch is also a part of homework and we will be graded for that!

**Comment by JustinJaniszewski** [comment]
No i did not delete it. I do not fully understand the branches myself. I think your branch can be found here:
https://github.com/reshnashrestha/23-Homework1G3

I do not know why it often creates the branch in your own repository instead of the "23-Homework1G3". It has done the same to me when I try to create branches in other groups.

**Comment by reshnashrestha** [comment]
Oh okay ! I was thinking that after merging branches are supposed to be showing up on the main repo. I am still confused.

**Comment by reshnashrestha** [comment]
@laserlab @ubsuny/cp23-1 what's the deal here? if anyone have any idea here?

**Comment by reshnashrestha** [comment]
I think it's like only the maintainer's branches are showing up in the homework main repository after merging .. whilst the merge requests made by other group members are not showing up in the main branch even though the changes appear in the main branch. This might be the default setting in our homework main repo. And to check up on how many branches are made by members, we can always check on the forked repo.

**Comment by laserlab** [comment]
Actually you (and in particular me) see if the merge request was made from the main branch or from something else. So that is no problem if it was merged in the main branch. If there are no more questions about this you can close this issue

**Comment by reshnashrestha** [comment]
Yes, Prof. I am good. Thank you !
