### ISSUE TITLE
Arithmetic function for the homework G4

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework1G3#3]
Hi There, 

this is to let you know that we, in G4, have chosen the multiplication function for our homework.
 
Please let us know the arithmetic function you've chosen. 

Good Luck

**Comment by reshnashrestha** [comment]
Hi @yasmensarhan27 , We have not decided about the arithmetic function yet. We will let you know soon.

**Comment by reshnashrestha** [comment]
noted
