### ISSUE TITLE
Contributor issue

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G3#30]
As I have done forking, created new branches, pulled and merged requests and commits in the main branch. However, the only contributors shown in the main branch are maintainers only.  
![image](https://github.com/ubsuny/23-Homework1G3/assets/143649458/36925077-ae01-4c7a-a769-e1a80cb42b33)
![image](https://github.com/ubsuny/23-Homework1G3/assets/143649458/53b4dd58-397b-4e4e-807d-5f873ef377a9)

So, to my understanding: only maintainers are seen as contributors. Is this okay or there are some mistakes? @ubsuny/cp23-1 @laserlab

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework1G3/assets/143649458/8bbe057a-b34d-493e-906c-11c75f745cdf)
@laserlab @JustinJaniszewski there is no contribution of mine visible in our homework G3 main repository. Could you explain what might be reasons?

**Comment by laserlab** [comment]
Not sure what the GitHub contributer list is sorted by. Could be number of lines of code added or changed. However important for the project is number of commits and merge request as written in the description and if you check that your name is shown at your commits and merge requests.

**Comment by reshnashrestha** [comment]
Yeah, I think it is like that because in that sense I have done multiple comits and merge requests, along with creating docstring for example unit tests, but still main repo is not showing my contributions. And, I was confused by that, however your response helped. Thank You @laserlab
