### ISSUE TITLE
Commit message problem

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework1G3#31]
@pratibha77118  I would recommend not using "Create process_for_division.md" as a commit message. We can tell you created process_for_division.md without you having to write it. You could write a bit of info about your document instead.

**Comment by pratibha77118** [comment]
Yes @JustinJaniszewski It happened accidently and is there any way to edit it? I tried to edit that commit title.

**Comment by JustinJaniszewski** [comment]
Ah okay. No worries then, just saying for future commits.
