### ISSUE TITLE
Can I change a merge request comment?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework1G3#32]
I accidently merged without changing the display message to something less messy looking. Is it possible to change this after I already accepted it?

**Comment by WildJimmy** [comment]
Yep. If you go to the page for pull requests, then click on "# closed", you can go to the page for the closed merge request. On the page for the merge request there should be an "edit" button in the top right corner that lets you change the comment

**Comment by JustinJaniszewski** [comment]
Thank you very much for your help
