### ISSUE TITLE
Cannot Update File

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G3#33]
@JustinJaniszewski  now after you have merged my pull request, I cannot edit my file too. Is this the way it works ?

**Comment by pratibha77118** [comment]
Also is there any way to delete the file you merged so that I will make another pull request.

**Comment by JustinJaniszewski** [comment]
Are you editing the same file? because then there is no need to delete it. You could make your edits and simply make another request.

**Comment by JustinJaniszewski** [comment]
oh sorry i didnt see the first comment. You have to click on the file then make sure to click the edit button in the top right. It looks like a pencil.

**Comment by pratibha77118** [comment]
I am editing the same file. Do I need to make another pull request? I simply changed the file name and commit message.

**Comment by pratibha77118** [comment]
I am making you another pull request then.
