### ISSUE TITLE
Unit testing 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework1G3#44]
Hi group3. How do you check unit testing ?

**Comment by reshnashrestha** [comment]
@JustinJaniszewski if you have any thoughts

**Comment by JustinJaniszewski** [comment]
Working on it. I had an example using basic python.

**Comment by JustinJaniszewski** [comment]
I added unit tests to our restoring division file

**Comment by pratibha77118** [comment]
@JustinJaniszewski you doing unit test of restoring division file. Have you tried it to implement on qiskit?
