### ISSUE TITLE
 Algorithm for division function

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G3#49]
I have not found any reliable solution to implement this division function. Though I learned about encoding input , I am still not clear on using the right quantum gates to implement this. Any suggestion is highly appreciated.

**Comment by reshnashrestha** [comment]
As we discussed earlier, this division function on quantum computers is more for educational purposes rather than practical. We can try. However, there will be restrictions.

**Comment by pratibha77118** [comment]
It seems so. I do tried to execute few algorithms but got circuit error each time.
