### ISSUE TITLE
Circuit Error

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G3#55]
While executing the  python code I got  the error:" CircuitError: Index 2 out of range for size ) " which means that there is an issue with my quantum circuit. It might be saying that I am trying to access or measure a qubit at index 2 but my quantum circuit does not  have that many qubit.
Are there any other  possible reason due to which I might have encountered this error?

**Comment by reshnashrestha** [comment]
Yes, this is the restriction we face while trying to run classical function on quantum computer.
