### ISSUE TITLE
Programming Platform

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework1G3#6]
How are we going to conduct our work? or which development platform? colab or VS ? or anything else?

**Comment by JustinJaniszewski** [comment]
I have used Jupyter notebook seperately before. We could use that however you have to download it. Maybe there is an easier alternative.

**Comment by JustinJaniszewski** [comment]
I remembered that I used replit.com in my coding class. I found it very easy to use. Just make an account and it will save everything online. You can also download your files from the site if needed.

**Comment by reshnashrestha** [comment]
Okay that sounds convenient.... 
But I am still figuring out the question.

**Comment by reshnashrestha** [comment]
So @JustinJaniszewski and @pratibha77118, I think that I will be using Visual Studio as IDE and IBM quantum Composer site for implementation.
