### ISSUE TITLE
Do I need to use the IBM computer site to start my python file?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework1G3#7]

**Comment by reshnashrestha** [comment]
I think other groups can suggest  this.

**Comment by reshnashrestha** [comment]
Hi, @JustinJaniszewski I think we need to use our IBM API key without committing (as mentioned in our HW description). As per my chat with @laserlab on discord 
![Uploading image.png…]()

**Comment by AhmedCode99** [comment]
You do not need the IBM computer. You can simulate everything in python using the qiskit library.

**Comment by JustinJaniszewski** [comment]
Thank you Ahmed
