### ISSUE TITLE
Starting with Algorithm 

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G3#8]
I am gonna start with algorithm. But for that I should be clear about what work/code we gonna implement.

**Comment by JustinJaniszewski** [comment]
I think we can start off with a function of 2 variables. This will just simply be dividing the first variable by the second. Then when running the function with any 2 numbers it will return the answer.

**Comment by reshnashrestha** [comment]
We can look at other groups' work. That way we can get a lead on how to proceed with tasks. @pratibha77118 @JustinJaniszewski   you can have a look at Group 1's work [https://github.com/ubsuny/23-Homework1G1/blob/main/quantum_multiplication_v2.py](url)
