### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework1G3#9]
Any thoughts on errors to test in the code?

**Comment by Mosaddeq107** [comment]
@JustinJaniszewski Can you please specify more?

**Comment by JustinJaniszewski** [comment]
@Mosaddeq107 so maybe an idea of what should be tested in a "good" unit test

**Comment by Mosaddeq107** [comment]
@JustinJaniszewski I got your point, but I need some time to answer you. By this time, anyone should help you.

**Comment by Pranjal-Srivastava-2023** [comment]
I have added comments to your unit test code. Sent you a merge request.
